backup_dest_user: backups
backup_dest_host: localhost
backup_dest_path: "/srv/rsync/{{ inventory_hostname }}"

ssh_key_path: "{{ ansible_env.HOME }}/.ssh/rsync_ed25519"
  
schedule_cron: true
cron_hour: '23'
cron_minute: '30'

restore_on_first_run: true