- hosts: all
  become: yes
  roles:
    - base
    - geerlingguy.docker
    - role: viasite-ansible.zsh
      zsh_antigen_bundles_extras:
        - nvm
        - joel-porquet/zsh-dircolors-solarized
      zsh_autosuggestions_bind_key: "^U"
      zsh_user: "{{ lookup('env', 'USER') }}"
    - vscode
    - role: 1password
      non_root_user: "{{ lookup('env', 'USER') }}"
    - common
    - inkscape
    - mpv
    - filezilla

- hosts: all
  become: no
  roles:
    - role: morgangraphics.nvm
      nvm_user: "{{ lookup('env', 'USER') }}"
    - role: git_config
      git_user_name: "Hermann Björgvin Haraldsson"
      git_user_email: "hermann@hermann.is"
    - role: gnome-settings
      my_user: "{{ lookup('env', 'USER') }}"

- hosts: desktop
  become: yes
  roles:
    - darktable
    - transmission
    - vlc

- hosts: laptop
  become: yes
  roles:
    - role: home-vpn-route
      route_ip: "192.168.2.145"
      interface_name: "Home"

- hosts: laptop
  become: no
  roles:
    - role: tvieira.powerline-fonts
      all_users:
        - user: hermann
          homedir: /home/hermann
      all_fonts:
        - AnonymousPro
        - FiraMono
        - Inconsolata
        - DejaVuSansMono
        - SourceCodePro
#    - role: osync
#      become: yes
#      sync_target_host: serverIP
#      sync_target_user: hermann
