- hosts: all
  become: yes
  roles:
    - base
    - geerlingguy.docker
    - role: viasite-ansible.zsh
      zsh_antigen_bundles_extras:
        - nvm
        - joel-porquet/zsh-dircolors-solarized
      zsh_autosuggestions_bind_key: "^U"
      zsh_user: "{{ lookup('env', 'USER') }}"
    - vscode
    - role: 1password
      non_root_user: "{{ lookup('env', 'USER') }}"
    - common
    - inkscape
    - mpv
    - filezilla

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - role: petermosmans.customize-gnome
  vars:
    gnome_dconf:
      - key: /org/gnome/desktop/background/show-desktop-icons
        value: "false"
      - key: /org/gnome/shell/favorite-apps
        value: "['firefox_firefox.desktop', 'code_code.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.Settings.desktop']"
    gnome_extensions:
      # https://extensions.gnome.org/extension/7174/nordvpn-quick-toggle/
      - id: 7174
        enable: yes
    gnome_user: "{{ lookup('env', 'USER') }}"
    customize_gnome__skip_restart_gnome_shell: true

- hosts: all
  become: no
  roles:
    - role: morgangraphics.nvm
      nvm_user: "{{ lookup('env', 'USER') }}"
    - role: git_config
      git_user_name: "Hermann Björgvin Haraldsson"
      git_user_email: "hermann@hermann.is"
    - role: gnome-settings
      my_user: "{{ lookup('env', 'USER') }}"
    - role: rsync
      non_root_user: "{{ lookup('env', 'USER') }}"
      backup_dest_user: backups
      backup_dest_host: ssh.earth
      backup_dest_path: "/srv/Backups/{{ inventory_hostname }}"
      cron_hour: '23'
      cron_minute: '30'

- hosts: desktop
  become: yes
  roles:
    - darktable
    - transmission
    - vlc

- hosts: laptop
  become: yes
  roles:
    - nordvpn
    - role: home-vpn-route
      route_ip: "192.168.2.145"
      interface_name: "Home"

- hosts: laptop
  become: no
  roles:
    - role: tvieira.powerline-fonts
      all_users:
        - user: hermann
          homedir: /home/hermann
      all_fonts:
        - AnonymousPro
        - FiraMono
        - Inconsolata
        - DejaVuSansMono
        - SourceCodePro