- hosts: all
  become: yes
  vars:
    zsh_antigen_bundles_extras:
      - nvm
    zsh_autosuggestions_bind_key: "^U"
  roles:
    - base
    - viasite-ansible.zsh
    - vscode
- hosts: all
  become: false # NVM should be installed as your regular user
  roles:
    - role: morgangraphics.ansible_role_nvm
      nvm_user: "{{ lookup('env', 'USER') }}"
