- name: Ensure snapd is installed
  apt:
    name: snapd
    state: present
    update_cache: yes

- name: Install Visual Studio Code via snap
  command: snap install --classic code
  args:
    creates: /snap/bin/code

- name: Install Visual Studio Code Insiders  via snap
  command: snap install --classic code-insiders
  args:
    creates: /snap/bin/code-insiders
