- name: Set Git global user.name
  community.general.git_config:
    scope: global
    name: user.name
    value: "{{ git_user_name }}"

- name: Set Git global user.email
  community.general.git_config:
    scope: global
    name: user.email
    value: "{{ git_user_email }}"

- name: Set Git global pull.rebase
  community.general.git_config:
    scope: global
    name: pull.rebase
    value: true