- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install some common packages
  apt:
    name:
      - dconf-editor
      - gnome-tweaks
      - gnome-shell-extension-manager
      - dmz-cursor-theme
      - smartmontools
      - smbclient
      - sshfs
      - neofetch
    state: present
