- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install build-essential, git, and make
  apt:
    name:
      - build-essential
      - git
      - make
    state: present
