- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install essential developer packages
  apt:
    name:
      - build-essential
      - make
      - gnupg
      - git
      - curl
      - wget
      - htop
      - unzip
      - tree
      - software-properties-common
      - jq
      - fonts-powerline
    state: present
