- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install essential developer packages
  apt:
    name:
      - build-essential # Compilers and libraries for building software
      - make # Build tool
      - gnupg
      - git
      - curl # Data transfer tool
      - wget # Download utility
      - htop # Interactive process viewer
      - unzip # Archive extraction
      - tree # Directory listing in a tree format
      - software-properties-common # For managing repositories/PPAs
      - jq # JSON processor
      - fonts-powerline
    state: present
